# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n8LBDDjMxYi08jXyvK5b1BnlkU6-T3ig
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle
from sklearn.datasets import load_iris

st.set_page_config(page_tittle="Iris Dashboard App", layout ="centered")
st.sidebar.header("Dashboard")

st.set_page_config(page_tittle="Iris halamandua", layout ="centered")
st.sidebar.header("halamandua")

st.set_page_config(page_tittle="Iris halamanketiga", layout ="centered")
st.sidebar.header("halamanketiga")
